// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDWrNNWMuWVr6KYuGRoSKK-FDi9yOD_Nk',
    appId: '1:846536249514:web:b4a1211e222936f6e600d3',
    messagingSenderId: '846536249514',
    projectId: 'dhoom-fb1c6',
    authDomain: 'dhoom-fb1c6.firebaseapp.com',
    storageBucket: 'dhoom-fb1c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9RoYDkrcAXtiPqzC56c7jlPzG8FsomtQ',
    appId: '1:846536249514:android:9fe212a6149937a7e600d3',
    messagingSenderId: '846536249514',
    projectId: 'dhoom-fb1c6',
    storageBucket: 'dhoom-fb1c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxAxUOfJknZtFieh0AKJAcZIEhJX_-9eU',
    appId: '1:846536249514:ios:a42baedc19f3bbb6e600d3',
    messagingSenderId: '846536249514',
    projectId: 'dhoom-fb1c6',
    storageBucket: 'dhoom-fb1c6.appspot.com',
    androidClientId: '846536249514-334ifb8ip0no1q57igntehrtvlvqnm9q.apps.googleusercontent.com',
    iosClientId: '846536249514-4p6jutts8sn955qdn01s5gps8oleis2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxAxUOfJknZtFieh0AKJAcZIEhJX_-9eU',
    appId: '1:846536249514:ios:22eee737a28a27a2e600d3',
    messagingSenderId: '846536249514',
    projectId: 'dhoom-fb1c6',
    storageBucket: 'dhoom-fb1c6.appspot.com',
    androidClientId: '846536249514-334ifb8ip0no1q57igntehrtvlvqnm9q.apps.googleusercontent.com',
    iosClientId: '846536249514-4qv0tqo7korng9c4sbuflfl2u94rrvte.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhoom.RunnerTests',
  );
}
