// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzhynT3_kqPl7vVJCSE3uO34fvyKZ-krs',
    appId: '1:443728162015:web:567d3e6da1b408a4ce4d6a',
    messagingSenderId: '443728162015',
    projectId: 'video-calling-d2336',
    authDomain: 'video-calling-d2336.firebaseapp.com',
    storageBucket: 'video-calling-d2336.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACWS3_NRryIxUzrai6L5sHVij_TCShnnY',
    appId: '1:443728162015:android:2a339d867192afadce4d6a',
    messagingSenderId: '443728162015',
    projectId: 'video-calling-d2336',
    storageBucket: 'video-calling-d2336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDai3Bo8Fv7vO1K9J-na-7lbwH58IakzEI',
    appId: '1:443728162015:ios:4d36a3c4933ebce8ce4d6a',
    messagingSenderId: '443728162015',
    projectId: 'video-calling-d2336',
    storageBucket: 'video-calling-d2336.appspot.com',
    androidClientId: '443728162015-hct9ngsgqn4147tbqesgmhpq3n62tt0r.apps.googleusercontent.com',
    iosClientId: '443728162015-4f2jhfkvvejngil035on25b1sloh100p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDai3Bo8Fv7vO1K9J-na-7lbwH58IakzEI',
    appId: '1:443728162015:ios:3faf84e543c3cc41ce4d6a',
    messagingSenderId: '443728162015',
    projectId: 'video-calling-d2336',
    storageBucket: 'video-calling-d2336.appspot.com',
    androidClientId: '443728162015-hct9ngsgqn4147tbqesgmhpq3n62tt0r.apps.googleusercontent.com',
    iosClientId: '443728162015-l0vtse2ecn8vv558qdnqb9r7mpri6fs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhoom.RunnerTests',
  );
}
